from tkinter import *

scr=Tk()
scr.geometry("1366x768")
scr.title("PIZZA SAFARI")
#scr.resizable(False, False)
scr.iconbitmap('../p.ico')
fr=Frame(scr,height=150,width=1366)
logo=PhotoImage(file="../logo1.png")
l=Label(fr,image=logo)
l.place(x=0,y=0)
fr.pack(fill=BOTH,expand=1)
fr1=Frame(scr,height=618,width=1366)
c=Canvas(fr1,height=618,width=1366)
c.pack()
back=PhotoImage(file="../pizzamain.png")
c.create_image(683,284,image=back)
lab=Button(fr1,text= "Click Here to enter the World of Pizzas",cursor="hand2", bd=4 ,font=("Brush Script MT",30, 'bold'),fg="black",bg="#9091e5")
lab.place(x=400,y=250)
fr1.pack(fill=BOTH,expand=1)
scr.mainloop()
