from tkinter import *
import random
import time
def Address():
    scr=Tk()
    scr.title("Janta Restaurant")
    scr.geometry("1366x768")
    #scr.resizable(False, False)
    fr=Frame(scr,height=150,width=1366)
    c=Canvas(fr,height=150,width=1366)
    c.pack()
    logo=PhotoImage(file="../logo.PNG")
    c.create_image(683,75,image=logo)
    home=Button(fr,text="Home",bg="#0b1335",cursor="hand2",fg="white",bd=5,font=("default",16,'bold'))
    home.place(x=1000,y=90)
    localtime=time.asctime(time.localtime(time.time()))
    c.create_text(1000,50,text=localtime,fill="white",font=("default",16))
    fr.pack(fill=BOTH,expand=1)

    f1=Frame(scr,height=618,width=1366)
    c=Canvas(f1,height=618,width=1366)
    c.pack()
    logo1=PhotoImage(file="../pizzamain.png")
    c.create_image(683,309,image=logo1)
    c.create_rectangle(50, 140, 1316, 420,fill="#d3ede6",outline="white",width=6)
    veg=PhotoImage(file="../veg.png")
    c.create_image(230,250,image=veg)
    vegbut=Button(f1,text="Veg Pizza",cursor="hand2",fg="white",bg="#0b1335",bd=5,font=("default",18,'bold'))
    vegbut.place(x=170,y=350)
    nonveg=PhotoImage(file="../Non.png")
    c.create_image(530,250,image=nonveg)
    nonvegbut=Button(f1,text="Non-Veg Pizza",cursor="hand2",fg="white",bg="#0b1335",bd=5,font=("default",18,'bold'))
    nonvegbut.place(x=440,y=350)
    chi=PhotoImage(file="../chiken.png")
    c.create_image(830,250,image=chi)
    chibut=Button(f1,text="Special Chicken",cursor="hand2",fg="white",bg="#0b1335",bd=5,font=("default",18,'bold'))
    chibut.place(x=730,y=350)
    side=PhotoImage(file="../extra.png")
    c.create_image(1130,250,image=side)
    sidebut=Button(f1,text="Sides and Beverages",cursor="hand2",fg="white",bg="#0b1335",bd=5,font=("default",18,'bold'))
    sidebut.place(x=1000,y=350)
    f1.pack(fill=BOTH,expand=1)
    scr.mainloop()

if __name__=="__main__":
    X=Address()
